import { describe, expect, it } from 'vitest';
import { col, fkCol, physical, pk, rel, table } from '../testing/physicalTestBuilders';
import { generateDdl } from './generateDdl';

/** Names of the created tables in script order. */
const createdTables = (ddl: string): string[] => [...ddl.matchAll(/^CREATE TABLE (\w+)/gm)].map((m) => m[1] as string);

describe('generateDdl', () => {
  it('generates CREATE TABLE statements with named constraints', () => {
    const m = physical(
      [
        table('Student', [
          col('Name', 'VARCHAR(100)', { isNotNull: true }),
          pk('Id', 'INTEGER', { isIdentity: true }),
          col('Email', 'VARCHAR(200)', { isUnique: true }),
          fkCol('SchoolId', 'r1', 'School.Id'),
        ]),
        table('School', [pk('Id')]),
      ],
      [rel('r1', 'School', 'Student')],
    );
    expect(generateDdl(m)).toBe(
      [
        '-- DDL generated by ER modeltool (standard SQL)',
        '',
        'CREATE TABLE School (',
        '    Id INTEGER NOT NULL,',
        '    CONSTRAINT PK_School PRIMARY KEY (Id)',
        ');',
        '',
        'CREATE TABLE Student (',
        '    Id INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,',
        '    Name VARCHAR(100) NOT NULL,',
        '    Email VARCHAR(200),',
        '    SchoolId INTEGER NOT NULL,',
        '    CONSTRAINT PK_Student PRIMARY KEY (Id),',
        '    CONSTRAINT UQ_Student_Email UNIQUE (Email),',
        '    CONSTRAINT FK_Student_School FOREIGN KEY (SchoolId) REFERENCES School (Id)',
        ');',
        '',
      ].join('\n'),
    );
  });

  it('orders tables topologically and keeps the model order otherwise', () => {
    const m = physical(
      [
        table('Grade', [pk('Id'), fkCol('StudentId', 'r2', 'Student.Id')]),
        table('Note', [pk('Id')]),
        table('Student', [pk('Id'), fkCol('SchoolId', 'r1', 'School.Id')]),
        table('School', [pk('Id')]),
      ],
      [rel('r1', 'School', 'Student'), rel('r2', 'Student', 'Grade')],
    );
    expect(createdTables(generateDdl(m))).toEqual(['Note', 'School', 'Student', 'Grade']);
  });

  it('keeps self references inline', () => {
    const m = physical([table('Employee', [pk('Id'), fkCol('ManagerId', 'r1', 'Employee.Id', 'INTEGER', { isNotNull: false })])], [rel('r1', 'Employee', 'Employee', 'zeroOrOne')]);
    const ddl = generateDdl(m);
    expect(ddl).toContain('    CONSTRAINT FK_Employee_Employee FOREIGN KEY (ManagerId) REFERENCES Employee (Id)\n);');
    expect(ddl).not.toContain('ALTER TABLE');
  });

  it('breaks cycles deterministically with ALTER TABLE at the end', () => {
    const m = physical(
      [table('A', [pk('Id'), fkCol('BId', 'r2', 'B.Id')]), table('B', [pk('Id'), fkCol('AId', 'r1', 'A.Id')])],
      [rel('r1', 'A', 'B'), rel('r2', 'B', 'A')],
    );
    const ddl = generateDdl(m);
    expect(createdTables(ddl)).toEqual(['A', 'B']);
    expect(ddl).toContain('CREATE TABLE A (\n    Id INTEGER NOT NULL,\n    BId INTEGER NOT NULL,\n    CONSTRAINT PK_A PRIMARY KEY (Id)\n);');
    expect(ddl).toContain('    CONSTRAINT FK_B_A FOREIGN KEY (AId) REFERENCES A (Id)\n);');
    expect(ddl.trimEnd().endsWith('ALTER TABLE A ADD CONSTRAINT FK_A_B FOREIGN KEY (BId) REFERENCES B (Id);')).toBe(true);
    expect(generateDdl(m)).toBe(ddl);
  });

  it('numbers colliding constraint names', () => {
    const m = physical(
      [
        table('Airport', [pk('Code', 'CHAR(3)')]),
        table('Flight', [pk('Nr'), fkCol('DepartureCode', 'r1', 'Airport.Code', 'CHAR(3)'), fkCol('ArrivalCode', 'r2', 'Airport.Code', 'CHAR(3)')]),
      ],
      [rel('r1', 'Airport', 'Flight'), rel('r2', 'Airport', 'Flight')],
    );
    const ddl = generateDdl(m);
    expect(ddl).toContain('CONSTRAINT FK_Flight_Airport FOREIGN KEY (DepartureCode) REFERENCES Airport (Code)');
    expect(ddl).toContain('CONSTRAINT FK_Flight_Airport2 FOREIGN KEY (ArrivalCode) REFERENCES Airport (Code)');
  });

  it('orders composite FK columns like the referenced key and writes unique constraints', () => {
    const m = physical(
      [
        table('Room', [pk('Building', 'CHAR(1)'), pk('Nr')]),
        table(
          'Beamer',
          [pk('Id'), fkCol('RoomNr', 'r1', 'Room.Nr'), fkCol('RoomBuilding', 'r1', 'Room.Building', 'CHAR(1)')],
          [
            { id: 'u1', name: '', columnIds: ['Beamer.RoomBuilding', 'Beamer.RoomNr'] },
            { id: 'u2', name: 'UQ_Custom', columnIds: ['Beamer.Id', 'Beamer.RoomNr'] },
          ],
        ),
      ],
      [rel('r1', 'Room', 'Beamer', 'one', 'zeroOrOne')],
    );
    const ddl = generateDdl(m);
    expect(ddl).toContain('CONSTRAINT PK_Room PRIMARY KEY (Building, Nr)');
    expect(ddl).toContain('CONSTRAINT FK_Beamer_Room FOREIGN KEY (RoomBuilding, RoomNr) REFERENCES Room (Building, Nr)');
    expect(ddl).toContain('CONSTRAINT UQ_Beamer_RoomBuilding_RoomNr UNIQUE (RoomBuilding, RoomNr)');
    expect(ddl).toContain('CONSTRAINT UQ_Custom UNIQUE (Id, RoomNr)');
  });

  it('lists key columns first and writes NULLable columns without NOT NULL', () => {
    const m = physical([table('Enrollment', [col('Note', 'VARCHAR(50)'), pk('StudentId'), pk('CourseId')])]);
    expect(generateDdl(m)).toContain(
      'CREATE TABLE Enrollment (\n    StudentId INTEGER NOT NULL,\n    CourseId INTEGER NOT NULL,\n    Note VARCHAR(50),\n    CONSTRAINT PK_Enrollment PRIMARY KEY (StudentId, CourseId)\n);',
    );
  });
});
