import { topologicalOrder } from '../graph/topologicalOrder';
import type { Column, PhysicalModel, Table } from '../model/physical';
import { uniqueName } from '../naming';
import { foreignKeyConstraints, type ForeignKeyConstraint } from './foreignKeyConstraints';

const INDENT = '    ';
const HEADER = '-- DDL generated by ER modeltool (standard SQL)';

interface NamedForeignKey extends ForeignKeyConstraint {
  name: string;
}

/**
 * Generates the standard SQL DDL script for a valid physical model (spec 5.4).
 *
 * Tables are ordered parents first, otherwise in model order. A cycle is broken by creating
 * the first remaining table in model order; FKs to tables created later are added with
 * ALTER TABLE at the end. Self references stay inline. Constraint names (PK_, UQ_, FK_)
 * are unique within the script. The output is deterministic.
 */
export function generateDdl(model: PhysicalModel): string {
  const allForeignKeys = foreignKeyConstraints(model);
  const order = topologicalOrder(model.tables, (t) => allForeignKeys.filter((fk) => fk.child === t).map((fk) => fk.parent));
  const position = new Map(order.map((t, i) => [t, i]));

  const takenNames: string[] = [];
  const nameOf = (base: string): string => {
    const name = uniqueName(base, takenNames);
    takenNames.push(name);
    return name;
  };

  const statements: string[] = [];
  const deferred: NamedForeignKey[] = [];
  for (const table of order) {
    const key = table.columns.filter((c) => c.isPrimaryKey);
    const constraints = [
      ...(key.length > 0 ? [`CONSTRAINT ${nameOf(`PK_${table.name}`)} PRIMARY KEY (${columnList(key)})`] : []),
      ...uniqueConstraints(table).map((u) => `CONSTRAINT ${nameOf(u.name)} UNIQUE (${columnList(u.columns)})`),
    ];
    for (const fk of allForeignKeys.filter((f) => f.child === table)) {
      const named: NamedForeignKey = { ...fk, name: nameOf(`FK_${table.name}_${fk.parent.name}`) };
      // The parent does not exist yet when it is created later (cycle).
      if ((position.get(fk.parent) ?? 0) > (position.get(table) ?? 0)) deferred.push(named);
      else constraints.push(foreignKeyClause(named));
    }
    statements.push(createTable(table, constraints));
  }
  statements.push(...deferred.map((fk) => `ALTER TABLE ${fk.child.name} ADD ${foreignKeyClause(fk)};`));

  return [HEADER, ...statements].join('\n\n') + '\n';
}

function createTable(table: Table, constraints: string[]): string {
  // Key columns come first, like in the diagram.
  const columns = [...table.columns.filter((c) => c.isPrimaryKey), ...table.columns.filter((c) => !c.isPrimaryKey)];
  const lines = [...columns.map(columnDefinition), ...constraints].map((l) => INDENT + l);
  return `CREATE TABLE ${table.name} (\n${lines.join(',\n')}\n);`;
}

function columnDefinition(column: Column): string {
  const parts = [column.name, column.dataType.trim()];
  if (column.isIdentity) parts.push('GENERATED ALWAYS AS IDENTITY');
  if (column.isNotNull || column.isPrimaryKey) parts.push('NOT NULL');
  return parts.filter((p) => p !== '').join(' ');
}

/** Single column UNIQUE flags (UQ_<Table>_<Col>) followed by the named multi column constraints. */
function uniqueConstraints(table: Table): { name: string; columns: Column[] }[] {
  const single = table.columns.filter((c) => c.isUnique).map((c) => ({ name: `UQ_${table.name}_${c.name}`, columns: [c] }));
  const named = table.uniqueConstraints
    .map((u) => {
      const columns = u.columnIds.flatMap((id) => table.columns.filter((c) => c.id === id));
      const name = u.name.trim() || `UQ_${table.name}_${columns.map((c) => c.name).join('_')}`;
      return { name, columns };
    })
    .filter((u) => u.columns.length > 0);
  return [...single, ...named];
}

function foreignKeyClause(fk: NamedForeignKey): string {
  return `CONSTRAINT ${fk.name} FOREIGN KEY (${columnList(fk.columns)}) REFERENCES ${fk.parent.name} (${columnList(fk.referencedColumns)})`;
}

function columnList(columns: readonly Column[]): string {
  return columns.map((c) => c.name).join(', ');
}
