import { newId } from '../ids';
import type { Id } from '../model/common';
import type { Column, PhysicalForeignKeyOrigin } from '../model/physical';
import { uniqueName } from '../naming';
import type { MappedForeignKey } from './foreignKeyRelationships';
import type { PlannedMember, PlannedTable } from './tablePlan';

/**
 * Builds the columns of the planned tables from their attributes (spec 4.2): data type empty,
 * NOT NULL for mandatory and key attributes, attribute order kept. Logical FK attributes become
 * FK columns of the mapped physical relationship (name and rename flag kept, so role names
 * survive); FK attributes that cannot be mapped are left out and regenerated by the FK sync.
 * Returns the columns by table id.
 */
export function buildColumns(
  tables: readonly PlannedTable[],
  mappedForeignKey: (logicalRelationshipId: Id, childTableId: Id) => MappedForeignKey | undefined,
): Map<Id, Column[]> {
  // Column ids are assigned up front because FK columns reference key columns of other tables.
  const columnIds = new Map<string, Id>();
  const key = (tableId: Id, attributeId: Id): string => `${tableId}|${attributeId}`;
  for (const table of tables) for (const m of table.members) columnIds.set(key(table.id, m.attribute.id), newId());

  const foreignKeyOrigin = (table: PlannedTable, member: PlannedMember): PhysicalForeignKeyOrigin | undefined => {
    const fk = member.attribute.fk;
    const mapped = fk && mappedForeignKey(fk.relationshipId, table.id);
    const referencedId = fk && mapped && columnIds.get(key(mapped.parentTableId, fk.referencedId));
    if (!fk || !mapped || !referencedId) return undefined;
    return { relationshipId: mapped.relationshipId, referencedId, isRenamed: fk.isRenamed, isTypeOverridden: false };
  };

  const result = new Map<Id, Column[]>();
  for (const table of tables) {
    const columns: Column[] = [];
    for (const member of table.members) {
      const { attribute, isForcedNullable } = member;
      const fk = foreignKeyOrigin(table, member);
      if (attribute.fk && !fk) continue;
      const isPrimaryKey = attribute.isPrimaryKey && !isForcedNullable;
      columns.push({
        id: columnIds.get(key(table.id, attribute.id)) as Id,
        // Rolled up subtype attributes may collide with supertype attributes.
        name: uniqueName(attribute.name, columns.map((c) => c.name)),
        dataType: '',
        isPrimaryKey,
        isNotNull: isPrimaryKey || (!attribute.isOptional && !isForcedNullable),
        isUnique: false,
        isIdentity: false,
        ...(fk ? { fk } : {}),
      });
    }
    result.set(table.id, columns);
  }
  return result;
}
