import { resolveRoles } from '../cardinality';
import { newId } from '../ids';
import type { Id, Relationship } from '../model/common';
import type { TablePlan } from './tablePlan';

/** Physical relationship that takes over the FK attributes of a logical one in a child table. */
export interface MappedForeignKey {
  relationshipId: Id;
  parentTableId: Id;
}

/** Result of mapping the 1:n and 1:1 relationships. */
export interface ForeignKeyRelationships {
  relationships: Relationship[];
  /**
   * Physical relationship whose FK columns in `childTableId` correspond to the logical FK
   * attributes of `logicalRelationshipId`. Undefined if the FKs cannot be taken over
   * (a rolled down parent needs one new FK per subtype table, generated by the FK sync).
   */
  mappedForeignKey(logicalRelationshipId: Id, childTableId: Id): MappedForeignKey | undefined;
}

/**
 * Maps the 1:n and 1:1 relationships to physical relationships between the planned tables
 * (cardinalities, identifying flag and anchors are kept). A relationship whose parent or
 * child is a rolled down supertype is created once per pair of tables. FKs that land in a
 * supertype table by roll up, and FKs to the tables of a rolled down supertype, become NULLable.
 */
export function mapForeignKeyRelationships(logical: readonly Relationship[], plan: TablePlan): ForeignKeyRelationships {
  const relationships: Relationship[] = [];
  const mapped = new Map<string, MappedForeignKey>();
  const key = (logicalId: Id, childTableId: Id): string => `${logicalId}|${childTableId}`;

  for (const rel of logical) {
    const roles = resolveRoles(rel);
    if (roles.kind === 'manyToMany') continue;
    const parentTables = plan.tablesOf(roles.parentId);
    const isParentOptional = parentTables.length > 1 || plan.isRolledUp(roles.childId);
    for (const child of plan.tablesOf(roles.childId)) {
      for (const parent of parentTables) {
        const [source, target] = roles.isReversed ? [child, parent] : [parent, child];
        const physical: Relationship = { ...rel, id: newId(), sourceId: source.id, targetId: target.id };
        relationships.push(isParentOptional ? withOptionalParent(physical) : physical);
        if (parentTables.length === 1) mapped.set(key(rel.id, child.id), { relationshipId: physical.id, parentTableId: parent.id });
      }
    }
  }
  return { relationships, mappedForeignKey: (logicalId, childTableId) => mapped.get(key(logicalId, childTableId)) };
}

/**
 * Makes the parent end optional ('zeroOrOne') so the diagram matches NULLable FK columns.
 * Such a relationship cannot be identifying. A 1:1 relationship gets 0..1 at both ends,
 * because `1` at the child end would turn the roles around (see resolveRoles); the line is
 * then oriented parent -> child, which keeps the roles for the symmetric case.
 */
function withOptionalParent(rel: Relationship): Relationship {
  const roles = resolveRoles(rel);
  if (roles.kind === 'manyToMany') return rel;
  const [parentAnchor, childAnchor] = roles.isReversed ? [rel.targetAnchor, rel.sourceAnchor] : [rel.sourceAnchor, rel.targetAnchor];
  const result: Relationship = {
    id: rel.id,
    sourceId: roles.parentId,
    targetId: roles.childId,
    sourceCardinality: 'zeroOrOne',
    targetCardinality: roles.kind === 'oneToOne' ? 'zeroOrOne' : roles.childCardinality,
    isIdentifying: false,
  };
  if (parentAnchor) result.sourceAnchor = parentAnchor;
  if (childAnchor) result.targetAnchor = childAnchor;
  return result;
}
